### ISSUE TITLE
CircleCI is not properly caching modules

### ISSUE THREAD

**Issue by hwh33** [getlantern/meta-scrubber#4]
If you look at the output on CircleCI runs, you will see statements like:
```
go: downloading github.com/stretchr/testify v1.6.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
```

This is despite us [attempting to cache these](https://github.com/getlantern/meta-scrubber/blob/4f3bd52d2576c795e32f343047596b671e2d1279/.circleci/config.yml#L21-L24).  It's not a big deal, just makes CI take slightly longer.

**Comment by max-b** [comment]
Ah those are all dev dependencies, and the circleci config is saving the cache after the build step but before the test step. I can make a quick PR to fix that.

**Comment by max-b** [comment]
Fixed! Thanks!!
